# This is a basic workflow to help you get started with Actions

name: Doxygen

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.2.3
        with:
          working-directory: './'
          doxyfile-path: 'docs/Doxyfile'

